blockchain:
  #挖矿难度值,越大越难挖
  mine_difficulty_value: 24
  #挖矿奖励代币数量
  token_reward_num: 25
  #交易池大小(满足多少条交易才开始进行挖矿)
  trade_pool_length: 2
  #日志存放路径
  log_path: "./logfile/"
  #中文助记词种子路径
  chinese_mnemonic_path: "./chinese_mnemonic_world.txt"
  # W 重HASH次数
  w_num: 100
network:
  #本地监听IP
  listen_host: "127.0.0.1"
  #本地监听端口
  listen_port: "8004"
  #节点组唯一标识名称(如果节点间名称不同会找不到网络)
  rendezvous_string: "user_net"
  #网络传输流的协议id(如果节点间id不同发送不了数据)
  protocol_id: "/chain/1.1.0"

  #云计算节点地址
  remote_host: "127.0.0.1"
  remote_port: "7003"
#  remote_host: "144.34.183.16"
#  remote_port: "7003"

user:
  #给予挖矿用户的奖励地址9003
  #this_node_addr: "1Bu3NhMG1YPDmTjxjFtuVkJ51DcURMqAFj"
  #9002
  #this_node_addr: "1EqGpmvreF6Vznfztn4vCg7xMRvChLFthD"
  #9004
  this_node_addr: "1EqGpmvreF6Vznfztn4vCg7xMRvChLFthD"

